version: 0.0
os: linux
files:
  - source: /propass-monolith-api/target/propass-monolith-api-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/propass-backend-monolith/propass-monolith-api/target/
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user